export enum Sections {
    ANIMATION_ENTRIES = "ANIMATION_ENTRIES",
    ADD_ANIMATION_ENTRY = "ADD_ANIMATION_ENTRY",
    ANIMATION_DEFINITIONS = "ANIMATION_DEFINITIONS",
    ANIMATION_DEFINITION = "ANIMATION_DEFINITION",
    MENU = "MENU",
    TIMELINES = "TIMELINES",
    PARALLAX_TIMELINES = "PARALLAX_TIMELINES",
    NUMBERS = "NUMBERS",
    BREAKPOINTS = "BREAKPOINTS",
}